services:
  loki:
    container_name: loki
    image: docker.io/grafana/loki:3.5.7
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - ./config/config.yaml:/etc/loki/config.yaml:ro
      - data_loki:/loki:rw
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.loki.entrypoints=websecure
      - traefik.http.routers.loki.rule=Host(`loki.dev.infra.orangewood.co`)
      - traefik.http.routers.loki.tls=true
      - traefik.http.routers.loki.tls.certresolver=websecure
volumes:
  data_loki:
    driver: local
networks:
  frontend:
    external: true